### ISSUE TITLE
does this part working in your container

### ISSUE THREAD

**Issue by comsompom** [Svajunas900/FastApiApp#3]
https://github.com/Svajunas900/FastApiApp/blob/0f13fc815dd8f25fd166381e63c046caeb06a601/Dockerfile#L9

Does it work?

**Comment by Svajunas900** [comment]
Yes, everything is working

**Comment by Svajunas900** [comment]
It does, everything is working. I with latest python image. Now I'm trying understand which slimmer version will work as well.

**Comment by Svajunas900** [comment]
It does, everything is working with latest python image. Now I'm trying understand which slimmer version will work as well.
